# Site settings
title: Editorial
subtitle: by HTML5 UP
email: youremailaddress@gmail.com
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/jon-vargas.github.io" # the subpath of your site, e.g. /blog
url: "jon-vargas.github.io" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
