# Site settings
title: Jonathan Vargas
subtitle: Jr. Data Analyast at Zillow
email: jonvargas157@gmail.com
description: Welcome and thanks for stopping by! I use this as my personal professional website to learn/develop skills and as a creative outlet to explore interests. 
baseurl: "/jon-vargas.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Jonathan Vargas
street_address: 1234 Somewhere Road
city:
state: California
zip_code:
country: United States of America
phone:
# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://www.instagram.com/johnnyvargas
linkedin_url: https://www.linkedin.com/in/jonathanvargas157
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
