# Site settings
title: Jonathan Vargas
subtitle: Jr. Data Analyast at Zillow
email: jonvargas157@gmail.com
description: Welcome and thanks for stopping by! I use this as my personal professional website to learn/develop skills and as a creative outlet to explore interests. 
baseurl: "/jon-vargas.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Jonathan Vargas
location: Orange County
country: USA
# Social settings
500px_url:
github_url:
instagram_url: https://www.instagram.com/johnnyvargas
linkedin_url: https://www.linkedin.com/in/jonathanvargas157

# Build settings
markdown: kramdown
